"""Constants for ALORAIR-Lite."""

DOMAIN = "alorair_lite"
CONF_MAC = "mac"
CONF_ALLOW_HTTP = "allow_insecure_http"
CONF_POLL_INTERVAL = "poll_interval"
CONF_EXPERIMENTAL = "experimental_controls"
CONF_TRANSPORT = "transport"
CONF_LISTEN_HOST = "listen_host"
CONF_LISTEN_PORT = "listen_port"
CONF_DEVICE_HOST = "device_host"
CONF_LOCAL_POWER = "allow_local_power"
TRANSPORT_CLOUD = "cloud"
TRANSPORT_LOCAL = "local"
DEFAULT_LOCAL_PORT = 6100
DEFAULT_POLL_INTERVAL = 30
MINIMUM_OFF_SECONDS = 180
PENDING_SECONDS = 300
MODE_CONTINUOUS = "continuous"
MODE_AUTO = "auto"
